export const PRODUCTS_LISTING = 'PRODUCTS_LISTING;';
export const PRODUCTS_PAGING = 'PRODUCTS_PAGING';
export const FAVORITES_LISTING = 'FAVORITES_LISTING;';
export const FAVORITES_PAGING = 'FAVORITES_PAGING';
