export const PRODUCTS_LISTING = 'PRODUCTS_LISTING;';
export const PRODUCTS_PAGING = 'PRODUCTS_PAGING';
export const PRODUCTS_ADD_FAVORITE = 'PRODUCTS_ADD_FAVORITE';
export const PRODUCTS_REMOVE_FAVORITE = 'PRODUCTS_REMOVE_FAVORITE';
export const FAVORITES_LISTING = 'FAVORITES_LISTING;';
export const FAVORITES_PAGING = 'FAVORITES_PAGING';
